# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7cfec1fa6c89b9387546be3016ef53e1e1310556ab52874a319993ac47ced0680e6f32b15b2ce56836816c796f46108c13b507cc303509e30a00d2408982ac73

test:
  secret_key_base: a6ae68b45f92ec520227c21ee72b09e73f478bdd30a1177ab69010fdc2b7cf9ef3d0004db3b462bc697350d6de95c98b2685e5729e564f90b4ee17737a47b0a3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
